export const SET_EVENTS = 'common/SET_EVENTS';
export const SET_EVENTS_LOADING = 'common/SET_EVENTS_LOADING';
export const SET_EVENTS_ERROR = 'common/SET_EVENTS_LOADING';

export const SET_PROJECTS_FOR_EVENT = 'common/SET_PROJECTS_FOR_EVENT';
export const SET_PROJECTS_FOR_EVENT_LOADING = 'common/SET_PROJECTS_FOR_EVENT_LOADING';
export const SET_PROJECTS_FOR_EVENT_ERROR = 'common/SET_PROJECTS_FOR_EVENT_ERROR';