export const SET_TOKEN = 'admin/SET_TOKEN';
export const SET_EVENTS = 'admin/SET_EVENTS';

export const SET_ANNOTATORS_FOR_EVENT = 'admin/SET_ANNOTATORS_FOR_EVENT';
export const SET_ANNOTATORS_LOADING_FOR_EVENT = 'admin/SET_ANNOTATORS_LOADING_FOR_EVENT';
export const SET_ANNOTATORS_ERROR_FOR_EVENT = 'admin/SET_ANNOTATORS_ERROR_FOR_EVENT';
