export const SET_TOKEN = 'admin/SET_TOKEN';
export const SET_EVENT = 'admin/SET_EVENT';
export const SET_EVENTS = 'admin/SET_EVENTS';

export const SET_ANNOTATORS_FOR_EVENT = 'admin/SET_ANNOTATORS_FOR_EVENT';
export const SET_ANNOTATORS_LOADING_FOR_EVENT = 'admin/SET_ANNOTATORS_LOADING_FOR_EVENT';
export const SET_ANNOTATORS_ERROR_FOR_EVENT = 'admin/SET_ANNOTATORS_ERROR_FOR_EVENT';

export const SET_PROJECTS_FOR_EVENT = 'admin/SET_PROJECTS_FOR_EVENT';
export const SET_PROJECTS_LOADING_FOR_EVENT = 'admin/SET_PROJECTS_LOADING_FOR_EVENT';
export const SET_PROJECTS_ERROR_FOR_EVENT = 'admin/SET_PROJECTS_ERROR_FOR_EVENT';
